export const projects = [
  {
    id: 1,
    title: "Bridal Makeup",
    description: "Elegant bridal transformations, timeless beauty, special occasions",
    image: "/models/model1.JPEG",
    column: 1,
  },
  {
    id: 2,
    title: "Editorial Makeup",
    description: "Creative artistry, photoshoot ready, high-fashion looks",
    image: "/models/model2.JPEG",
    column: 1,
  },
  {
    id: 3,
    title: "Natural Glam",
    description: "Everyday elegance, subtle enhancement, natural beauty",
    image: "/models/model5.JPEG",
    column: 1,
  },
  {
    id: 4,
    title: "Evening Makeup",
    description: "Glamorous evening looks, special events, sophisticated style",
    image: "/models/model4.JPG",
    column: 1,
  },
  // {
  //   id: 5,
  //   title: "Artistic Makeup",
  //   description: "Creative expression, bold looks, artistic transformations",
  //   image: "/models/model5.JPEG",
  //   column: 1,
  // },
  {
    id: 6,
    title: "Professional Makeup",
    description: "Business ready, polished looks, confidence boosting",
    image: "/models/model6.JPEG",
    column: 1,
  },
  // {
  //   id: 7,
  //   title: "Special Event Makeup",
  //   description: "Party ready, celebration looks, memorable moments",
  //   image: "/models/model7.JPEG",
  //   column: 1,
  // },
  {
    id: 8,
    title: "Photoshoot Makeup",
    description: "Camera ready, studio quality, professional results",
    image: "/models/model9.JPEG",
    column: 1,
  },
  {
    id: 9,
    title: "Custom Makeup",
    description: "Personalized looks, tailored to you, unique style",
    image: "/models/model10.JPEG",
    column: 1,
  },
  {
    id: 10,
    title: "Glamour Makeup",
    description: "Red carpet ready, luxury beauty, premium service",
    image: "/models/model11.JPEG",
    column: 1,
  },
  {
    id: 11,
    title: "Beauty Transformation",
    description: "Complete makeovers, style enhancement, confidence building",
    image: "/models/model12.JPEG",
    column: 1,
  },
  {
    id: 12,
    title: "Luxury Makeup Service",
    description: "Premium experience, expert artistry, flawless finish",
    image: "/models/model13.JPEG",
    column: 1,
  },
];
