export const projects = [
  {
    id: 1,
    title: "RizzBrand AI — Dreamscape Series",
    description: "Art Installation, Visual Effects, Photography",
    image: "/projects/project7.jpg",
    link: "https://rizzbrand.site",
    column: 1,
  },
  {
    id: 2,
    title: "Creators Brand Pitch",
    description: "Creative Campaign, Augmented Reality, Interactive Design",
    image: "/projects/project2.jpg",
    column: 1,
  },
  {
    id: 3,
    title: "Saas Website Builder",
    description: "Lighting Design, Concept Art, Event Production",
    image: "/projects/project3.jpg",
    column: 1,
  },
  {
    id: 4,
    title: "Rizzbrand Creators (2025)",
    description: "Set Design, Experimental Film, Soundscape",
    image: "/projects/project4.jpg",
    column: 1,
  },
  {
    id: 5,
    title: "Creators Podcast",
    description: "Fashion Collaboration, Editorial, Immersive Media",
    image: "/projects/project5.jpg",
    column: 2,
  },
  {
    id: 6,
    title: "RizzCard - Empowering visionaries",
    description: "Music Video, Color Grading, 3D Environments",
    image: "/projects/project6.jpg",
    column: 2,
  },
  {
    id: 7,
    title: "Rizzbrand Site",
    description:
      "Interactive Installation, Projection Mapping, Visual Identity",
    image: "/projects/project1.jpg",
    column: 2,
  },
  {
    id: 8,
    title: "Advertisments",
    description: "Cinematic Trailer, Narrative Design, VFX",
    image: "/projects/project8.jpg",
    column: 2,
  },
];
